In [5]:
#과제 2-1 (오류 코드)

import pandas as pd
import numpy as np
data = {
'Name' : ['철수', '영희', '진희', '정혁'],
'Age' : [17, 23, 42, 29],
'City' : ['서울', '부산', '인천', '광주']
}

df = pd.DataFrame(data)

df['Salary'] = [5000, 650, 2400]

ValueError: ignored

In [7]:
# 오류 해결 - 값이 3개가 아닌 4개가 들어가야 함

df['Salary'] = [5000, 650, 2400, 5200]

df

  Name  Age City  Salary
0   철수   17   서울    5000
1   영희   23   부산     650
2   진희   42   인천    2400
3   정혁   29   광주    5200

In [8]:
#과제 2-2 (오류 코드)

import torch

def multiply_tensors (a, b) :
  c = a * b
  return c

tensor1 = torch.tensor([2, 4, 6])
tensor2 = torch.tensor([1, 3])

result = multiply_tensors(tensor1, tensor2)

print(result)

RuntimeError: ignored

In [9]:
# 오류 해결 - elementwise multiplication을 하려면 개수가 맞아야 함

tensor1 = torch.tensor([2, 4, 6])
tensor2 = torch.tensor([1, 3, 5])

result = multiply_tensors(tensor1, tensor2)

print(result)

tensor([ 2, 12, 30])